services:

  nginx:
    image: nginx:alpine
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./app
    container_name: devops-backend
    expose:
      - "5000"
    environment:
      DB_HOST: database
      DB_NAME: trainee_db
      DB_USER: trainee
      DB_PASSWORD: postgres
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    container_name: devops-postgres
    environment:
      POSTGRES_DB: trainee_db
      POSTGRES_USER: trainee
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trainee -d trainee_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: devops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: devops-node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  postgres_data:
